services:
  api:
    build: .
    hostname: "api"
    ports:
      - "8080:8080"
    environment:
      MODE: "api"
    volumes:
      - ./api:/app/api
      - ./common:/app/common
  camera:
    build: .
    environment:
      MODE: "camera"
      API_BASE_URL: "http://api:8080"
    volumes:
      - ./camera:/app/camera
      - ./common:/app/common
    depends_on:
      - "api"
